version: '3.2'
services:
  teaching_api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=teaching_api
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - TWO_FACTOR_BASE_URL=https://2factor.in/API
      - JWT_SECRET=secret_KEsdfsdfjkshdfkja2kjh34kj2h3
      - JWT_REFRESH_SECRET=4kjhg34kjg5j3h4g5jhg34
      - JWT_EXPIRES_IN=7d
      - JWT_REFRESH_EXPIRES_IN=30
      - 2FACTOR_API_KEY=e22905d7-a75a-11ec-a4c2-0200cd936042

    networks:
      - englishniti-backend
    depends_on:
      - postgres

  postgres:
    image: postgres:10.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teaching_api
    volumes:
      - ../teaching_api-data:/var/lib/postgresql/data
    ports:
      - '5432'

    networks:
      - englishniti-backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mohamedbalshy2014@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - englishniti-backend


networks:
  englishniti-backend:
    driver: bridge
   
volumes:
  pgadmin-data:
    driver: local